---
- name: reload pf
  shell: /sbin/pfctl -f /etc/pf.conf

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart unbound
  service:
    name: unbound
    state: restarted

- name: restart dhcpd
  service:
    name: isc-dhcpd
    state: restarted
